"""add automod, boosterrole, voicemaster, vanity, error_log tables

Revision ID: 0aaa4ab140bf
Revises: 6b7df4a2fba8
Create Date: 2026-06-29 09:20:01.006259
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0aaa4ab140bf'
down_revision: str | None = '6b7df4a2fba8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automod_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('log_only', sa.Boolean(), nullable=False),
    sa.Column('dm_on_action', sa.Boolean(), nullable=False),
    sa.Column('exempt_mods', sa.Boolean(), nullable=False),
    sa.Column('strike_window_hours', sa.Integer(), nullable=False),
    sa.Column('filter_invites', sa.Boolean(), nullable=False),
    sa.Column('filter_links', sa.Boolean(), nullable=False),
    sa.Column('filter_spam', sa.Boolean(), nullable=False),
    sa.Column('spam_count', sa.Integer(), nullable=False),
    sa.Column('spam_interval', sa.Integer(), nullable=False),
    sa.Column('duplicate_threshold', sa.Integer(), nullable=False),
    sa.Column('filter_mentions', sa.Boolean(), nullable=False),
    sa.Column('mention_limit', sa.Integer(), nullable=False),
    sa.Column('block_everyone', sa.Boolean(), nullable=False),
    sa.Column('filter_words', sa.Boolean(), nullable=False),
    sa.Column('filter_caps', sa.Boolean(), nullable=False),
    sa.Column('caps_percent', sa.Integer(), nullable=False),
    sa.Column('caps_min_len', sa.Integer(), nullable=False),
    sa.Column('filter_emoji', sa.Boolean(), nullable=False),
    sa.Column('emoji_limit', sa.Integer(), nullable=False),
    sa.Column('timeout_at', sa.Integer(), nullable=False),
    sa.Column('timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('timeout2_at', sa.Integer(), nullable=False),
    sa.Column('timeout2_minutes', sa.Integer(), nullable=False),
    sa.Column('kick_at', sa.Integer(), nullable=False),
    sa.Column('ban_at', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('automod_domains',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'domain', name='uq_automoddomain_guild_domain')
    )
    op.create_table('automod_exempt_channels',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'channel_id', name='uq_automodexchan_guild_channel')
    )
    op.create_table('automod_exempt_roles',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'role_id', name='uq_automodexrole_guild_role')
    )
    op.create_table('automod_words',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'word', name='uq_automodword_guild_word')
    )
    op.create_table('booster_role_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('hoist_above', sa.Boolean(), nullable=False),
    sa.Column('anchor_role_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('booster_roles',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', name='uq_boosterrole_guild_user')
    )
    op.create_table('error_logs',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('context', sa.String(length=200), nullable=False),
    sa.Column('exc_type', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_error_logs_code', 'error_logs', ['code'], unique=False)
    op.create_table('vanity_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('message_template', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('vanity_trackers',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', name='uq_vanitytracker_guild_user')
    )
    op.create_table('voicemaster_channels',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'channel_id', name='uq_vmchannel_guild_channel')
    )
    op.create_table('voicemaster_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('create_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('panel_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('panel_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_index('ix_mod_cases_guild_user_kind_created', 'mod_cases', ['guild_id', 'user_id', 'kind', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mod_cases_guild_user_kind_created', table_name='mod_cases')
    op.drop_table('voicemaster_config')
    op.drop_table('voicemaster_channels')
    op.drop_table('vanity_trackers')
    op.drop_table('vanity_config')
    op.drop_index('ix_error_logs_code', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_table('booster_roles')
    op.drop_table('booster_role_config')
    op.drop_table('automod_words')
    op.drop_table('automod_exempt_roles')
    op.drop_table('automod_exempt_channels')
    op.drop_table('automod_domains')
    op.drop_table('automod_config')
    # ### end Alembic commands ###
