"""initial schema

Revision ID: 6b7df4a2fba8
Revises: 
Create Date: 2026-06-27 05:16:34.689328
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '6b7df4a2fba8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('button_roles',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('emoji', sa.String(length=64), nullable=True),
    sa.Column('style', sa.String(length=16), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_buttonrole_message', 'button_roles', ['message_id'], unique=False)
    op.create_table('channel_multipliers',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'channel_id', name='uq_chanmult_guild_channel')
    )
    op.create_table('guild_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('prefix', sa.String(length=8), nullable=True),
    sa.Column('log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('log_joins', sa.Boolean(), nullable=False),
    sa.Column('log_leaves', sa.Boolean(), nullable=False),
    sa.Column('log_message_delete', sa.Boolean(), nullable=False),
    sa.Column('log_message_edit', sa.Boolean(), nullable=False),
    sa.Column('log_mod_actions', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('immune_entries',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('is_role', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'target_id', name='uq_immune_guild_target')
    )
    op.create_table('jailed_members',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('prior_roles', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', name='uq_jailed_guild_user')
    )
    op.create_table('level_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('xp_per_message', sa.Integer(), nullable=False),
    sa.Column('message_cooldown', sa.Integer(), nullable=False),
    sa.Column('announce_mode', sa.String(length=8), nullable=False),
    sa.Column('announce_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('level_up_message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('level_rewards',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'level', name='uq_levelreward_guild_level')
    )
    op.create_table('managed_webhooks',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('webhook_id', sa.BigInteger(), nullable=False),
    sa.Column('short_id', sa.String(length=12), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'short_id', name='uq_webhook_guild_short')
    )
    op.create_table('member_levels',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('xp', sa.BigInteger(), nullable=False),
    sa.Column('voice_minutes', sa.BigInteger(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', name='uq_memberlevel_guild_user')
    )
    op.create_index('ix_memberlevel_guild_voice', 'member_levels', ['guild_id', 'voice_minutes'], unique=False)
    op.create_index('ix_memberlevel_guild_xp', 'member_levels', ['guild_id', 'xp'], unique=False)
    op.create_table('mod_cases',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mod_cases_guild_user', 'mod_cases', ['guild_id', 'user_id'], unique=False)
    op.create_table('moderation_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('jail_role_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('players',
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('wallet', sa.BigInteger(), nullable=False),
    sa.Column('vault', sa.BigInteger(), nullable=False),
    sa.Column('vault_capacity', sa.BigInteger(), nullable=False),
    sa.Column('generator_tier', sa.Integer(), nullable=False),
    sa.Column('generator_claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_daily_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_work_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_pray_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_steal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('vault <= vault_capacity', name='chk_player_vault_within_cap'),
    sa.CheckConstraint('vault >= 0', name='chk_player_vault_nonneg'),
    sa.CheckConstraint('vault_capacity >= 0', name='chk_player_vault_cap_nonneg'),
    sa.CheckConstraint('wallet >= 0', name='chk_player_wallet_nonneg'),
    sa.PrimaryKeyConstraint('discord_id')
    )
    op.create_index('ix_players_net_worth', 'players', [sa.literal_column('(wallet + vault) DESC')], unique=False)
    op.create_table('reaction_roles',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('emoji', sa.String(length=64), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'emoji', name='uq_reactionrole_msg_emoji')
    )
    op.create_index('ix_reactionrole_message', 'reaction_roles', ['message_id'], unique=False)
    op.create_table('reminders',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.String(length=1500), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminders_remind_at', 'reminders', ['remind_at'], unique=False)
    op.create_table('sticky_messages',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('last_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('temp_roles',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temp_roles_expires', 'temp_roles', ['expires_at'], unique=False)
    op.create_table('timers',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timers_next_run', 'timers', ['next_run'], unique=False)
    op.create_table('transactions',
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('counterparty_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('game_session_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_game_session', 'transactions', ['game_session_id'], unique=False)
    op.create_index('ix_transactions_type', 'transactions', ['kind'], unique=False)
    op.create_index('ix_transactions_user_time', 'transactions', ['discord_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_time', table_name='transactions')
    op.drop_index('ix_transactions_type', table_name='transactions')
    op.drop_index('ix_transactions_game_session', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_timers_next_run', table_name='timers')
    op.drop_table('timers')
    op.drop_index('ix_temp_roles_expires', table_name='temp_roles')
    op.drop_table('temp_roles')
    op.drop_table('sticky_messages')
    op.drop_index('ix_reminders_remind_at', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index('ix_reactionrole_message', table_name='reaction_roles')
    op.drop_table('reaction_roles')
    op.drop_index('ix_players_net_worth', table_name='players')
    op.drop_table('players')
    op.drop_table('moderation_config')
    op.drop_index('ix_mod_cases_guild_user', table_name='mod_cases')
    op.drop_table('mod_cases')
    op.drop_index('ix_memberlevel_guild_xp', table_name='member_levels')
    op.drop_index('ix_memberlevel_guild_voice', table_name='member_levels')
    op.drop_table('member_levels')
    op.drop_table('managed_webhooks')
    op.drop_table('level_rewards')
    op.drop_table('level_config')
    op.drop_table('jailed_members')
    op.drop_table('immune_entries')
    op.drop_table('guild_config')
    op.drop_table('channel_multipliers')
    op.drop_index('ix_buttonrole_message', table_name='button_roles')
    op.drop_table('button_roles')
    # ### end Alembic commands ###
